name: Integração Contínua com Github Actions

on:
  push:
    branches: 
     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Imprimir Diretório de Trabalho
        run: pwd

      - name: Login no Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Configurar JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: Compilar com Maven
        working-directory: ./rest-with-spring-boot-and-java-erudio
        run:  mvn clean package

      - name: Construir Docker Compose
        working-directory: .
        run: docker compose build

      - name: Enviar para o Registro de Contêineres do Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}

          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest
